version: '3.8'

services:
  my-app:
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - my-db
    
  
  my-db:
    image: redis:alpine
    #volumes:
     # - ./db_data:/data