apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask
  template:
    metadata:
      labels:
        app: my-flask
    spec:
      containers:
      - name: flask-app
        image: awdadawdargrg/my-flask-app:latest
        ports:
        - containerPort: 5000
        env: 
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"